### ISSUE TITLE
Error in latest image

### ISSUE THREAD

**Issue by sagarjauhari** [meAmidos/dcind#17]
sh: declare: not found

![image](https://user-images.githubusercontent.com/1958807/60911433-fb07bc80-a237-11e9-815c-7bec5b487a17.png)

**Comment by sagarjauhari** [comment]
Note: `sha256:3c176a1df007201276564610f5c40fd3b56179c6ee75f23199f4ff508c28e6f5` is working fine.

**Comment by DBarney** [comment]
yeah the main `docker-lib.sh` script changed from using `sh` to using `bash`: https://github.com/meAmidos/dcind/blob/53e9db8b2d9ab13ead7fb1be0c33136a6ded5f02/docker-lib.sh#L1.

Really though, @meAmidos should be exposing more tags than just `latest`, so that anyone who is using their images will not have to worry about breaking changes being introduced on a whim.

**Comment by meAmidos** [comment]
Agreed. Using semver tagging would have helped to avoid the issue. Meanwhile, I'll see if I could rectify the issue for those who depend on the `latest` image.

**Comment by meAmidos** [comment]
The new `latest` image should now work again in old CI pipelines. Further releases will follow the semver rules.
