### ISSUE TITLE
Can you provide this image on something other than alpine?

### ISSUE THREAD

**Issue by jeanbza** [meAmidos/dcind#3]
Ubuntu perhaps?

**Comment by meAmidos** [comment]
This image is intentionally built on top of Alpine to serve as a lightweight tool. It works perfectly for its initial purpose of running Docker Compose in Docker, so, I would rather not add anything to it, unless it's essential.

That being said, you can always fork the repo and customize the Dockerfile for your needs. Could you share please, what is your use case and what are you trying to achieve by using Ubuntu instead of Alpine in this image?
